### ISSUE TITLE
FHEM Residents Modul offiziell portiert

### ISSUE THREAD

**Issue by jpawlowski** [nollhome/ioBroker.residents#1]
Ich habe das FHEM RESIDENTS Modul inzwischen "offiziell" in einen ioBroker Adapter portiert, der hier zu finden ist:
https://github.com/jpawlowski/ioBroker.residents

Dachte das wäre interessant hier zu erwähnen. Die Logik ist auf die ioBroker Möglichkeiten angepasst. Da Einschränkungen von der FHEM-Systemarchitektur nicht mehr zutreffen, sind auch bereits einige Verbesserungen eingeflossen.

**Comment by nollhome** [comment]
Hi Julian,
danke dass du den Adapter übernommen hast. Ich hatte mal das Bestreben, den FHEM Adapter nachzubauen, allerdings fehlte mir dann die Zeit, mich generell in die Adapterentwicklung einzuarbeiten.

Ich habe mir gleich mal die Beta installiert und werde mittesten (wenn es die Zeit zulässt).
Mir ist allerdings aufgefallen, dass wenn man auf das kleine Fragezeichen in der Adapter-Instanz klickt, man noch auf meine GITHub Seite gelangt. Vielleicht sollte man das noch anpassen :)

**Comment by jpawlowski** [comment]
Hi,

ich habe nix übernommen, das ist ein Irrtum. Habe deinen Adapter hier erst gerade bei der Suche entdeckt. Die Verlinkung ist auf meinen Adapter, hast nicht richtig geguckt ;-)

**Comment by nollhome** [comment]
Hab das Problem mittlerweile lokalisieren können.
Der Adapter, den ich begonnen hatte, war in iobroker noch installiert, als ich deine Beta installiert habe und da scheinen sich die Adapter vermischt zu haben.
Außer dem Link wurde auch die Version meines Adapters angezeigt.

Hab nochmal alles deinstalliert und erneut installiert. Jetzt passt es :)
